servidores: "localhost:9090"
debug: ${DEBUG_LOG:false}
trace: ${TRACE_LOG:false}
logging:
   level:
      root: ERROR
      org.springframework.test.context.support: OFF
      org.springframework.context.annotation: ERROR
      org.springframework.test: OFF
      org.apache.kafka.clients: WARN
      o.a.kafka.common.utils: OFF
      o.a.kafka.common.utils.AppInfoParser: OFF
server:
   port: ${SERVER_PORT_kafka_CONSUMO:8182}
   compression:
      enabled: true
      min-response-size: 1
spring:
   profiles:
      active: dev
   application:
      name: '@projet.artifactId@'